"""field email for model ban

Revision ID: 6bdb46fe5dff
Revises: bf97f90db26f
Create Date: 2021-10-23 22:30:54.654357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bdb46fe5dff'
down_revision = 'bf97f90db26f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Bans', sa.Column('email', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_Bans_email'), 'Bans', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Bans_email'), table_name='Bans')
    op.drop_column('Bans', 'email')
    # ### end Alembic commands ###
